Update ec-client-qa.yml

diff --git a/.github/workflows/ec-client-qa.yml b/.github/workflows/ec-client-qa.yml
--- a/.github/workflows/ec-client-qa.yml
+++ b/.github/workflows/ec-client-qa.yml
@@ -28,44 +28,44 @@ jobs:
             ssh-keyscan -H ${{ secrets.DEPLOY_HOST_PROD }} >> ~/.ssh/known_hosts
   
             # Use expect to add passphrase-protected key to ssh-agent
-            which expect || (sudo apt-get update && sudo apt-get install -y expect)
-            eval "$(ssh-agent -s)"
+          #  which expect || (sudo apt-get update && sudo apt-get install -y expect)
+          #  eval "$(ssh-agent -s)"
             # Debug: List the contents of ~/.ssh to verify key presence
-            echo "Listing ~/.ssh contents:"
-            ls -l /root/.ssh/
+          #  echo "Listing ~/.ssh contents:"
+          #  ls -l /root/.ssh/
 
             # Debug: Show the key file
-            echo "Private key file content:"
-            cat /root/.ssh/id_rsa_target
-            echo "Manually adding key to ssh-agent..."
-            ssh-add /root/.ssh/id_rsa_target
-            ssh-add -l  # List keys loaded in the agent to verify
+          #  echo "Private key file content:"
+          #  cat /root/.ssh/id_rsa_target
+          #  echo "Manually adding key to ssh-agent..."
+          #  ssh-add /root/.ssh/id_rsa_target
+          #  ssh-add -l  # List keys loaded in the agent to verify
             # Use 'expect' to add passphrase-protected key to ssh-agent
-            expect << EOF
-              spawn ssh-add /root/.ssh/id_rsa_target  # Ensure the correct absolute path
-              expect {
-                "Enter passphrase for /root/.ssh/id_rsa_target:" {
-                  send "${{ secrets.DEPLOY_HOST_PROD_KEY_PASSPHRASE }}\r"  # Provide the correct passphrase
-                  exp_continue
-                }
-                timeout {
-                  send_user "Timeout while waiting for passphrase prompt\n"
-                  exit 1
-                }
-                eof {
-                  send_user "Passphrase added successfully to agent\n"
-                }
-              }
-            EOF
+           # expect << EOF
+           #   spawn ssh-add /root/.ssh/id_rsa_target  # Ensure the correct absolute path
+           #   expect {
+           #     "Enter passphrase for /root/.ssh/id_rsa_target:" {
+           #       send "${{ secrets.DEPLOY_HOST_PROD_KEY_PASSPHRASE }}\r"  # Provide the correct passphrase
+           #       exp_continue
+           #     }
+           #     timeout {
+           #       send_user "Timeout while waiting for passphrase prompt\n"
+           #       exit 1
+           #     }
+           #     eof {
+           #       send_user "Passphrase added successfully to agent\n"
+           #     }
+           #   }
+           # EOF
             # Check if the ssh-add was successful
-            if [[ $? -eq 0 ]]; then
-              echo "SSH key added to agent successfully."
-            else
-              echo "Failed to add SSH key to agent."
-              exit 1
-            fi
+            #if [[ $? -eq 0 ]]; then
+           #   echo "SSH key added to agent successfully."
+           # else
+           #   echo "Failed to add SSH key to agent."
+           #   exit 1
+           # fi
             # Run SCP to Server B
-            scp -o StrictHostKeyChecking=no /var/tmp/ecclient.tar ${{ secrets.DEPLY_HOST_PROD_USER }}@${{ secrets.DEPLOY_HOST_PROD }}:/var/tmp/ecclient.tar
+            scp -i /root/.ssh/id_rsa_target -o StrictHostKeyChecking=no /var/tmp/ecclient.tar ${{ secrets.DEPLY_HOST_PROD_USER }}@${{ secrets.DEPLOY_HOST_PROD }}:/var/tmp/ecclient.tar
 
             #chmod 666 /var/tmp/ecclient.tar
             #echo "Docker image saved successfully."
